### ISSUE TITLE
Design Outreach object based on Spreadsheet

### ISSUE THREAD

**Issue by poofyOwl** [master-recycler-vancouver/mrv-outreach-tracker#1]
- [x] Emily provides spreadsheet
- [x] Design Outreach object
- [x] Create migration and update schema
- [x] Configure Rails model

**Comment by masterrecyclervan** [comment]
See spreadsheet here: https://docs.google.com/spreadsheets/d/1rZIbI2kWC_TVt2ubOgdFGIjhhx72VFJYDh8jwQG4LCs/edit?usp=sharing

**Comment by masterrecyclervan** [comment]
See the form: https://docs.google.com/forms/d/1KDw92ag7eo6CguDnK5jfe_MGesfIRHBDoEJn_raO8lg/edit
